# Generated by Django 5.0.6 on 2026-04-06 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_correo_alter_cliente_nombre'),
        ('envios', '0002_initial'),
        ('infraestructura_bodegas', '0003_alter_bodega_options_alter_ubicacion_options'),
        ('inventario', '0002_alter_inventario_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Stock actual disponible. Nunca puede ser negativo.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada modificación.'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(help_text='Producto al que pertenece este inventario.', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(help_text='Ubicación física dentro de la bodega.', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='infraestructura_bodegas.ubicacion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.IntegerField(help_text='Unidades movidas. Mínimo 1.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='envio_producto',
            field=models.ForeignKey(blank=True, help_text='Vínculo al despacho si la salida fue automática.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='envios.envioproducto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='observacion',
            field=models.TextField(blank=True, help_text='Contexto adicional del movimiento.'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(help_text='Producto afectado por el movimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], help_text="'entrada' para ingresos, 'salida' para despachos.", max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente propietario del producto.', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o características adicionales.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre único del producto por cliente.', max_length=200),
        ),
    ]
