# Generated by Django 5.0.6 on 2026-03-12 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modulo', models.CharField(choices=[('envios', 'Envíos'), ('inventario', 'Inventario'), ('servicios', 'Servicios'), ('facturacion', 'Facturación'), ('pagos', 'Pagos'), ('clientes', 'Clientes'), ('usuarios', 'Usuarios')], max_length=20)),
                ('accion', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
