# Generated by Django 5.0.6 on 2026-04-06 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_correo_alter_cliente_nombre'),
        ('facturacion', '0002_alter_detallefactura_cantidad_and_more'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realiza el pago.', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(help_text='Factura que se está pagando. Se conserva null si la factura es eliminada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en que se realizó el pago.'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], help_text='Forma de pago utilizada.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto total pagado en COP.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, help_text='Notas adicionales opcionales.'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de transferencia, cheque u otro comprobante.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario admin que registró el pago en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
