# Generated by Django 5.0.6 on 2026-03-06 17:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Producto en Envío',
                'verbose_name_plural': 'Productos en Envío',
            },
        ),
        migrations.CreateModel(
            name='OrdenEnvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('valor_flete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Envío',
                'verbose_name_plural': 'Órdenes de Envío',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
