# Generated by Django 5.0.6 on 2026-03-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_correo_alter_cliente_nombre'),
        ('envios', '0001_initial'),
        ('inventario', '0001_initial'),
        ('transportadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='ordenenvio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_envio', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordenenvio',
            name='transportador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='transportadores.transportador'),
        ),
        migrations.AddField(
            model_name='envioproducto',
            name='orden_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='envios.ordenenvio'),
        ),
    ]
