# Generated by Django 5.0.6 on 2026-03-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenenvio',
            name='valor_flete',
        ),
    ]
