# Generated by Django 5.0.6 on 2026-03-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura_bodegas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
