# Generated by Django 5.0.6 on 2026-03-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura_bodegas', '0002_alter_ubicacion_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['nombre'], 'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['bodega__nombre', 'codigo'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
