# Generated by Django 5.0.6 on 2026-03-18 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_correo_alter_cliente_nombre'),
        ('envios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('por_dia', 'Por día'), ('por_envio', 'Por envío'), ('por_recepcion', 'Por recepción'), ('unitario', 'Unitario')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Servicio',
                'verbose_name_plural': 'Catálogo de Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServicioPrestado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('facturado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('catalogo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.catalogoservicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestados', to='clientes.cliente')),
                ('orden_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='envios.ordenenvio')),
            ],
            options={
                'verbose_name': 'Servicio Prestado',
                'verbose_name_plural': 'Servicios Prestados',
                'ordering': ['-fecha'],
            },
        ),
    ]
