# Generated by Django 5.0.6 on 2026-03-07 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarifa_acordada', models.DecimalField(decimal_places=2, help_text='Tarifa pactada con este cliente. Si es 0 usa la tarifa del catálogo.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('catalogo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.catalogoservicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_servicio', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato de Servicio',
                'verbose_name_plural': 'Contratos de Servicio',
                'unique_together': {('cliente', 'catalogo_servicio')},
            },
        ),
        migrations.AddField(
            model_name='servicioprestado',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_prestados', to='servicios.contratoservicio'),
        ),
    ]
