# Generated by Django 5.0.6 on 2026-03-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoservicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo de Servicio', 'verbose_name_plural': 'Catálogo de Servicios'},
        ),
    ]
