# Generated by Django 5.0.6 on 2026-03-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_contratoservicio_servicioprestado_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioprestado',
            name='contrato',
        ),
        migrations.AddField(
            model_name='servicioprestado',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContratoServicio',
        ),
    ]
