# Generated by Django 5.0.6 on 2026-04-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_correo_alter_cliente_nombre'),
        ('facturacion', '0001_initial'),
        ('servicios', '0002_alter_catalogoservicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad del servicio prestado.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(help_text='Nombre del servicio al momento de facturar.', max_length=300),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(help_text='Factura a la que pertenece este detalle.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='servicio_prestado',
            field=models.ForeignKey(help_text='Servicio que origina este detalle.', on_delete=django.db.models.deletion.CASCADE, to='servicios.servicioprestado'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Total de esta línea: cantidad * valor_unitario.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Tarifa unitaria al momento de facturar.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente al que se emite la factura.', on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', help_text='Estado actual de la factura.', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, help_text='Fecha de creación de la factura (automática).'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Fecha límite de pago.'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA del 19% calculado sobre el subtotal.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Generado automáticamente en formato FAC-XXXX.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de todos los servicios antes de impuestos.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total a pagar: subtotal + impuestos.', max_digits=12),
        ),
    ]
