# Generated by Django 5.0.6 on 2026-03-06 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('moto', 'Moto'), ('camioneta', 'Camioneta'), ('camion', 'Camión'), ('furgon', 'Furgón')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transportador',
                'verbose_name_plural': 'Transportadores',
            },
        ),
    ]
