# Generated by Django 5.0.6 on 2026-03-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportador',
            options={'ordering': ['nombre'], 'verbose_name': 'Transportador', 'verbose_name_plural': 'Transportadores'},
        ),
    ]
